export const types = Object.freeze({
    // Sync
    USERS_START_FETCHING: 'USERS_START_FETCHING',
    USERS_STOP_FETCHING: 'USERS_STOP_FETCHING',
    USERS_FILL: 'USERS_FILL',
    USERS_SET_FETCHING_ERROR: 'USERS_SET_FETCHING_ERROR',
    // Async
    USERS_FETCH_ASYNC: 'USERS_FETCH_ASYNC',
});
